version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
    - discovery.type=single-node
    - cluster.routing.allocation.disk.threshold_enabled=true
    - cluster.routing.allocation.disk.watermark.low=65%
    - cluster.routing.allocation.disk.watermark.high=70%
    - xpack.security.enabled=true
    - xpack.security.audit.enabled=true
    - ELASTIC_PASSWORD=test
    ports:
      - 9200:9200
    healthcheck:
      interval: 10s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 900M

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 900M

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    command: >
      apm-server -e
        -E monitoring.enabled=true
        -E apm-server.expvar.enabled=true
        -E apm-server.instrumentation.enabled=true
        -E output.elasticsearch.hosts=["http://es-container:9200"]
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=test
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 8200:8200

  webapp:
    build:
      context: src
      # target: release
      dockerfile: Dockerfile.dev
    container_name: webapp
    restart: unless-stopped
    # volumes:
    #   - "./src/app/migrations/versions:/app/migrations/versions"
    depends_on:
      - postgres
    ports:
      - "7000:80"
    environment:
      SERVER_DEVELOPMENT: "True"
      LOG_LEVEL: debug

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

      
  docs:
      build:
          context: src
          dockerfile: Dockerfile.docs
      container_name: docs
      restart: always
      ports:
          - '7100:8000'
      logging:
          options:
              max-size: "512m"

volumes:
  db:
